github: lachlanchen
custom:
  - https://github.com/sponsors/lachlanchen
  - https://lazying.art
  - https://chat.lazying.art
  - https://onlyideas.art
  - https://chat.lazying.art/donate
paypal: RongzhouChen
